on: [push, pull_request]

name: Continuous integration

jobs:
  cargo:
    name: Cargo
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          # - stable
          - beta
          # - nightly
    steps:
      - run: apt update && apt install -y libasound2-dev libudev-dev cloc
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          components: rustfmt, clippy
      - run: cloc src
      - uses: Swatinem/rust-cache@v2
      - run: cargo check
      - run: cargo fmt --all -- --check
      - run: cargo clippy -- -D warnings
      - run: cargo build
      - run: cargo test --features ci
  
  markdown:
    name: Markdown lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actionshub/markdownlint@v3.1.4
